# Generated by Django 2.0.2 on 2018-03-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroExercicio', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
                ('resposta', models.CharField(max_length=100)),
            ],
        ),
    ]
