# Generated by Django 2.0.2 on 2018-04-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='numeroExercicio',
            field=models.CharField(max_length=4),
        ),
    ]
