# Generated by Django 2.0.2 on 2018-04-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0002_auto_20180403_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='codigo',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
