# Generated by Django 2.0.2 on 2018-04-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0003_exercicio_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='codigo',
            new_name='codigo_desenvolvido',
        ),
    ]
