# Generated by Django 2.0.2 on 2018-03-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUsuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
